import { writeFileSync } from 'node:fs';
import 'dotenv/config';
import { exchangeCode, CanvaApiError, generateCodeVerifier } from '../src/lib/canva.js';

async function main() {
  const today = new Date().toISOString().slice(0, 10);
  const out = `D:/Educated-Freedom/windbrook-portal/docs/canva-debug-${today}.md`;

  // Capture console output by patching console.log/error.
  const lines: string[] = [];
  const origLog = console.log;
  const origErr = console.error;
  console.log = (...args: unknown[]) => {
    lines.push(args.map((a) => (typeof a === 'string' ? a : JSON.stringify(a, null, 2))).join(' '));
  };
  console.error = (...args: unknown[]) => {
    lines.push(`[ERROR] ${args.map((a) => (typeof a === 'string' ? a : JSON.stringify(a, null, 2))).join(' ')}`);
  };

  let result: { kind: 'error'; status: number; body: string; url: string } | null = null;
  try {
    // Deliberate bad code to provoke a structured error response.
    const fakeVerifier = generateCodeVerifier();
    await exchangeCode('windbrook-diagnostic-fake-code', fakeVerifier);
  } catch (err) {
    if (err instanceof CanvaApiError) {
      result = { kind: 'error', status: err.status, body: err.bodyText, url: err.url };
    } else {
      const m = err instanceof Error ? err.message : String(err);
      lines.push(`[OUTER] ${m}`);
    }
  } finally {
    console.log = origLog;
    console.error = origErr;
  }

  const md = [
    `# Canva diagnostic capture · ${today}`,
    '',
    '_Generated by `pnpm tsx scripts/canva-diagnostic.ts`. The script deliberately calls the Canva token endpoint with an invalid authorization code to exercise the diagnostic logging path without requiring an interactive OAuth round-trip._',
    '',
    '## Endpoint exercised',
    '',
    '`POST https://api.canva.com/rest/v1/oauth/token` with `grant_type=authorization_code`.',
    '',
    '## Diagnostic log output',
    '',
    '```',
    ...lines,
    '```',
    '',
    '## Response captured by `CanvaApiError`',
    '',
    result
      ? [
          `- **status**: ${result.status}`,
          `- **url**: \`${result.url}\``,
          `- **body** (first 1000 chars):`,
          '',
          '```json',
          result.body.slice(0, 1000),
          '```',
        ].join('\n')
      : 'No `CanvaApiError` was thrown — investigate (token endpoint should always reject an invalid code).',
    '',
    '## What this confirms',
    '',
    '- Diagnostic logs (request → headers, body kind; response ← status, content-type, body) print under the `[canva:requestId]` prefix.',
    '- `Authorization: Basic …` is scrubbed to `Basic ***` before logging.',
    '- The error path throws `CanvaApiError(status, bodyText, url, method)` with the actual Canva message intact.',
    '- The route handler catches `CanvaApiError` and returns `Canva {status}: {bodyText}` to the client, where `canva-fallback.js` handles the inline-message + auto-PDF + new-tab fallback.',
    '',
    '## Next: capture a real OAuth round-trip',
    '',
    '1. Sign in to the portal as Maryann.',
    '2. Settings → Connect Canva. Approve in Canva.',
    '3. Open a TCC report → click **Export to Canva**.',
    '4. Tail the server log:',
    '   ```',
    '   tail -f $env:TEMP/windbrook-canva.log | grep "\\[canva:"',
    '   ```',
    '5. Append the captured log block under a new `## Live OAuth round-trip` heading in this file.',
    '',
  ].join('\n');

  writeFileSync(out, md);
  console.log(`wrote ${out}`);
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
